# Generated by Django 4.2.11 on 2025-02-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='parking_space',
            new_name='airconditioning',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='floor_number',
            new_name='stories',
        ),
        migrations.RemoveField(
            model_name='property',
            name='building_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='road_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='road_width',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
        migrations.AddField(
            model_name='property',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishingstatus',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='guestroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='hotwaterheating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='mainroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='prefarea',
            field=models.BooleanField(default=False),
        ),
    ]
