# Generated by Django 4.2.11 on 2025-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_parking_space_property_airconditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0),
        ),
    ]
