# Generated by Django 4.2.11 on 2025-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_property_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
