# Generated by Django 4.2.11 on 2025-02-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_property_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='prefarea',
        ),
    ]
