# Generated by Django 4.2.11 on 2025-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_remove_property_prefarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('ktm', 'Kathmandu'), ('bkt', 'Bhaktapur'), ('lat', 'Lalitpur')], max_length=100),
        ),
    ]
