# Generated by Django 4.2.11 on 2025-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
