# Generated by Django 4.2.11 on 2025-02-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_property_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(),
        ),
    ]
