# Generated by Django 4.2.11 on 2025-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_property_city_alter_property_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sale_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('ktm', 'Kathmandu'), ('bkt', 'Bhaktapur'), ('lat', 'Lalitpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0),
        ),
    ]
