# Generated by Django 4.2.11 on 2025-02-17 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_property_sale_status_alter_property_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(help_text='Area in square feet', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stories', models.FloatField(help_text='Number of floors', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('road_width', models.FloatField(help_text='Width of road in feet', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('city', models.CharField(choices=[('Bhaktapur', 'Bhaktapur'), ('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur')], help_text='City location', max_length=20)),
                ('road_type', models.CharField(choices=[('Blacktopped', 'Blacktopped'), ('Gravelled', 'Gravelled'), ('Soil_Stabilized', 'Soil Stabilized')], help_text='Type of road', max_length=20)),
                ('svm_prediction', models.FloatField(blank=True, help_text='Price prediction from SVM model', null=True)),
                ('dt_prediction', models.FloatField(blank=True, help_text='Price prediction from Decision Tree model', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'House Price Prediction',
                'verbose_name_plural': 'House Price Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('feature_scaler', 'Feature Scaler'), ('svm', 'Support Vector Machine'), ('decision_tree', 'Decision Tree'), ('feature_names', 'Feature Names')], max_length=20)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
