# Generated by Django 4.2.11 on 2025-02-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_alter_property_seller'),
        ('house', '0012_housepriceprediction_mlmodel'),
    ]

    operations = [
    ]
